version: '3.9' # optional since v1.27.0
services:
  docker-frontend:
    build:
      context: angular-crash-2021
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./angular-crash-2021/src:/frontend/src